### ISSUE TITLE
如何在IDEA 中测试呢

### ISSUE THREAD

**Issue by zuodengchao** [dongkelun/S3_Demo#1]

**Comment by dongkelun** [comment]
@zuodengchao 你指的Spark还是Flink

**Comment by zuodengchao** [comment]
> @zuodengchao 你指的Spark还是Flink

我想要使用MinIo 作为存储，如何在Flink配置呢？

**Comment by dongkelun** [comment]
> > @zuodengchao 你指的Spark还是Flink
> 
> Flink

Flink有找到本地扩展Flink plugins的方法,所以采用打包的方式

**Comment by dongkelun** [comment]
> 

这个没有经验，就只用过ceph

**Comment by zuodengchao** [comment]
> > > @zuodengchao 你指的Spark还是Flink
> > 
> > 
> > Flink
> 
> Flink有找到本地扩展Flink plugins的方法,所以采用打包的方式

可以在IDEA中配置吗

**Comment by dongkelun** [comment]
> > @zuodengchao 你指的Spark还是Flink
> 
> 我想要使用MinIo 作为存储，如何在Flink配置呢？

这个没有经验，就只用过ceph

**Comment by dongkelun** [comment]
> > > > @zuodengchao 你指的Spark还是Flink
> > > 
> > > 
> > > Flink
> > 
> > 
> > Flink有找到本地扩展Flink plugins的方法,所以采用打包的方式
> 
> 可以在IDEA中配置吗

我的意思就是不清楚，怎么在idea怎么配置扩展plugins，这个应该和flink有关，flink用的不多~

**Comment by zuodengchao** [comment]
OK, Thank you very much.
